project:
  type: website
  output-dir: docs
  resources: resources

website:
  title: "Tanzira Najnin"
  search: false
  favicon: "resources/favicon-32x32.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
  page-footer:
    left: "This site was created with [Quarto](https://quarto.org/), an open source scientific publishing system. To see the code that generates this site, [visit the repo here]()."
    

format:
  html:
    theme: flatly
    toc: true

editor: visual

execute:
  freeze: auto


