---
title: "Projects"
format: html
editor: visual
---

* [Facial Keypoints Detection](https://github.com/Tanzira/FacialKeypointDetection)\
    Implemented a CNN model for facial key points detection with ~75% accuracy on a kaggle image dataset.

* [Densenet Model Comparison](https://github.com/Tanzira/densenet_model_comparison)\
  Trained and compared variations of densenet model with other known models including resnet and efficientnet. Compared using Imagenet, SVHN, CIFAR10, CIFAR100 and ICSC datasets.
  We included another dataset that had skin lesion images and classified those as well.


* [Data Invariat Robust Models with Transfer Learning](https://github.com/Tanzira/Data-Invariat-Robust-Models-with-Transfer-Learning)\
  For this project I explored Data Invariance and model prediction using a simple example with the MNIST dataset. 
  At first the model performed well on MNIST dataset but it was not well suited for other dataset.
  Later  I applied transfer learning by leveraging the Xception model pretrained on the ImageNet dataset to enhance the accuracy of a flower classification model and achieved ~81% accuracy.
  I included another dataset that had skin lesion images and classified those as well.

* [Single-cell decomposition analysis to predict breast cancer Metastasis](https://github.com/Tanzira/single_cell_decomposition)\
  Here I used single-cell expression to decompose microarray gene expression data by clustering patients into multiple groups based on their gene expression. Used that to predict if a patient is going to have breast cancer metastasis or not.


* [Cache Memory Simulator.](https://github.com/Tanzira/CacheSimulator)\
  Developed a cache simulator for computer architecture course project.

* [Decaf-19 Compiler](https://github.com/Tanzira/Decaf-19)\
  Built a compiler for the Decaf19 programming language using python from scratch.Includes fully functional lexical analyser, parser, semantic analyser, and code generator.