---
title: "Publications"
format: html
editor: visual
---



### In Progress

A Novel Approach for Predicting Breast Cancer Metastasis. **Tanzira Najnin**, Sakhawat Hossain Saimon, Maryam Zand, Nahim Adnan, Zhijie Liu, Tim Hui-Ming Huang, and Jianhua Ruan

* Built class-specific gene networks and applied the network differences to classify breast cancer metastasis.
* Outperformed state-of-the-art models including Random Forest, Multi-layer Perceptron, and SVM.
* Analyzed model interpretability and ability to explain and highlight underlying biology.


A Novel Numeric Data Augmentation Techinique. Sakhawat Hossain Saimon, **Tanzira Najnin**, and Jianhua Ruan

* Designed an algorithm for augmenting high-dimensional numeric data and resolving class imbalance.
* Assessed post-augmentation performance of machine learning models using multiple metrics.
* Outperformed SMOTE and other state-of-the-art tools on a majority of 62 benchmarking datasets.


Single-cell biomarker gap junction gene panel for the non-surgical diagnosis of endometriosis: a proof-of-concept study. Li-Ling Lin, **Tanzira Najnin**, Chun-Wei Chen, Mia S. Ramos, Maricar Galang, Jeffery Chavez, Bijaya Nayak, Chiou-Miin Wang, Sakhawat H. Saimon, Randall D. Robinson, Jianhua Ruan, Bruce J Nicholson, Nameer B Kirma

* Developed an expression profile-based diagnosis tool for endometriosis, a surgically diagnosed disease.
* Achieved 99% prediction accuracy using an ensemble of random forest and support vector classifiers.


### 2023

[A Network-Based Approach for Improving Annotation of Transcription Factor Functions and Binding Sites in Arabidopsis thaliana](https://www.mdpi.com/2073-4425/14/2/282) 2023. **Tanzira Najnin**, Sakhawat Hossain Saimon, Garry Sunter, Jianhua Ruan. *Genes 14(2), 282*.


### 2022

[A Robust Personalized Classification Method for Breast Cancer Metastasis Prediction](https://www.mdpi.com/2072-6694/14/21/5327). 2022. Nahim Adnan, **Tanzira Najnin**, Jianhua Ruan. *Cancers 14 (21), 5327.*
